# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_RSMC2_rcpp_hello_world`)
}

weighted_quantile_cpp <- function(x, w, q) {
    .Call(`_RSMC2_weighted_quantile_cpp`, x, w, q)
}

